### ISSUE TITLE
Error while loading font_px2pt_923fonts.cp 

### ISSUE THREAD

**Issue by subramanyakrishna** [LaJoKoch/SynthTextGerman#2]
**Error :** 
PS C:\SynthTextGerman> & C:/Users/Admin/anaconda3/envs/env1/python.exe c:/SynthTextGerman/gen_more.py
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
getting data..
        -> done
Storing the output in: results/SynthText_8000.h5
Traceback (most recent call last):
  File "c:/SynthTextGerman/gen_more.py", line 146, in <module>
    main(args.viz)
  File "c:/SynthTextGerman/gen_more.py", line 86, in main        
    RV3 = RendererV3(DATA_PATH, max_time=SECS_PER_IMG)
  File "c:\SynthTextGerman\synthgen.py", line 373, in __init__   
    self.text_renderer = tu.RenderFont(data_dir)
  File "c:\SynthTextGerman\text_utils.py", line 119, in __init__ 
    self.font_state = FontState(data_dir)
  File "c:\SynthTextGerman\text_utils.py", line 450, in __init__ 
    p = u.load()
  File "C:\Users\Admin\anaconda3\envs\env1\lib\pickle.py", line 1212, in load
    dispatch[key[0]](self)
  File "C:\Users\Admin\anaconda3\envs\env1\lib\pickle.py", line 1337, in load_string
    self.append(self._decode_string(codecs.escape_decode(data)[0]))
  File "C:\Users\Admin\anaconda3\envs\env1\lib\pickle.py", line 1328, in _decode_string
    return value.decode(self.encoding, self.errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9c in position 0: invalid start byte

**packages : conda list**
packages in environment at C:\Users\Admin\anaconda3\envs\env1:

 Name       ----------------Version------------Build  Channel
autopep8         ------------ 1.5.7       ------------       pyhd3eb1b0_0
ca-certificates  ------------2021.7.5        ------------     haa95532_1
certifi          ------------       2020.12.5        ------------        pypi_0    pypi
cycler ------------0.10.0              ------------     pypi_0    pypi
h5py   ------------ 3.2.1            ------------        pypi_0    pypi
kiwisolver  ------------1.3.1         ------------           pypi_0    pypi
matplotlib   ------------3.4.1          ------------          pypi_0    pypi
numpy   ------------1.20.2              ------------     pypi_0    pypi
opencv-contrib-python  --4.5.1.48     ------------           pypi_0    pypi
openssl ------------1.1.1k        ------------       h2bbff1b_0
pickle4  ------------ 0.0.1           ------------         pypi_0    pypi
pillow    ------------8.2.0             ------------       pypi_0    pypi
pip       ------------21.2.2        ------------   py38haa95532_0
pycodestyle  ------------2.7.0       ------------       pyhd3eb1b0_0
pygame     ------------1.9.6          ------------          pypi_0    pypi
pyparsing  ------------ 2.4.7       ------------      pypi_0    pypi
python   ------------ 3.8.11         ------------ h6244533_0_cpython
python-dateutil ------2.8.1         ------------           pypi_0    pypi
python-wget ------------3.2       ------------                 py_0    conda-forge
python_abi------------3.8           ------------           2_cp38    conda-forge
pytz ------------ 2021.1           ------------        pypi_0    pypi
scipy ------------1.6.2             ------------       pypi_0    pypi
setuptools ------------ 49.6.0        ------------           pypi_0    pypi
six    ------------1.15.0             ------------      pypi_0    pypi
snakeviz  ------------ 2.1.0        ------------          pypi_0    pypi
sqlite  ------------ 3.36.0          ------------     h2bbff1b_0
toml   ------------0.10.2        ------------     pyhd3eb1b0_0
tornado  ------------6.1        ------------              pypi_0    pypi
vc   ------------14.1       ------------          h0510ff6_4    anaconda
vs2015_runtime  ------------14.27.29016          h5e58377_2
wheel------------0.36.2       ------------      pyhd3eb1b0_0
wincertstore ------------  0.2        ------------              py38_0

**I did the following :** 
1) Run add_more_data.py 
2) Run update_freq.py 
3)   gen_more.py but getting above error, I tried resolving this But couldn't, 
There is a problem with loading font_px2pt_923fonts.cp and When i cloned it there was no font_px2pt_923fonts.cp So I renamed  font_px2pt.cp to  font_px2pt_923fonts.cp.  And Even fonts was not there so I downloaded some fonts listed online and placed in fonts folder.  
Please help us in resolving this issue

**Comment by LaJoKoch** [comment]
`font_px2pt_923fonts.cp` is, as the name suggests, based on a specific list of fonts. You can show them up in `fontlist.txt`. But the fonts itself are not included in the repository. Therefore, you have to get some fonts on your own and based on them, you have to generate the corresponding font model with `invert_font_size.py`. The `fontlist.txt` has to get updated after that as well. It's also important that all characters of your text base are supported by the included fonts. You can test your fonts with the script `test_fonts.py`.

**Comment by subramanyakrishna** [comment]
ok Thank You Sir.
